### ISSUE TITLE
Dates on NYU manager role are listed in reverse order

### ISSUE THREAD

**Issue by micheletepper** [MaxWhitney/maxwhitney.github.io#1]
Unless this is some sort of Benjamin Button situation, you did not have that job from 2014 to 2011.
<img width="589" alt="screen shot 2018-02-22 at 2 34 20 pm" src="https://user-images.githubusercontent.com/3901131/36559976-83dda1b4-17dd-11e8-819f-92fe4e730b4f.png">

**Comment by MaxWhitney** [comment]
Thank you! Corrected in commit a495e6174df27bb3309eefae0fce45fedb6d9d6d
